name: TegraExplorer builder

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    container: devkitpro/devkita64

    steps:
    - uses: actions/checkout@v1
        
    - name: Build TegraExplorer
      run: |
        sudo apt update -y
        sudo apt install build-essential -y
        
        sudo apt install software-properties-common -y
        sudo add-apt-repository ppa:deadsnakes/ppa -y
        sudo apt install python3.9 -y
        sudo rm /usr/bin/python3
        sudo ln -s python3.9 /usr/bin/python3
        
        make -j$(nproc)
        
    - uses: actions/upload-artifact@master
      with:
        name: TegraExplorer
        path: | 
          output/TegraExplorer.bin
          output/TegraExplorer_small.bin
